services:
  app:
    build: .
    container_name: EveEnv
    entrypoint:
    - sleep
    - infinity
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - .:/root/code
